{% set version = "0.2.1" %}


package:
  name: deprecation-factory
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/deprecation-factory/deprecation_factory-{{ version }}.tar.gz
  sha256: b73988875ed151b8f7695cabb7510ebd6b2b2669e2383a5ecd2b64703b8c4912

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python >=3.5
    - pip
    - setuptools
  run:
    - python >=3.5

test:
  requires:
    - pytest
    - numpydoc
  imports:
    - deprecation_factory
  commands:
    - pytest --pyargs deprecation_factory

about:
  home: https://github.com/hmaarrfk/deprecation_factory
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Automatically write boilerplate code for many kinds of deperecations through python decorators.'
  description: |
    Breaking things is important! Breaking other's things is just mean!

    This Python3 library provides decorators to avoid writing boilerplate code for many kinds of
    deprecations. Currently, we support deprecating the default value of `kwargs`
  doc_url: https://deprecation-factory.readthedocs.io/en/latest/?badge=latest
  dev_url: https://github.com/hmaarrfk/deprecation_factory

extra:
  recipe-maintainers:
    - hmaarrfk
