travis:
  secure:
    BINSTAR_TOKEN: G0ZA+pP5lCy1xJ872I62APIRV1WL94S4i57YE6+PDfyOKEKTuWBaAQAQOlNCq0HbXrUMmm9SmwM8CZ5nbf8cWcPt/Wo1HVOUovYaOohN7lqmLgXIylo7ncXbookbin+6tM1tgoKvcidJ9RZiiaD6trxNefIXHYaP85LeBVuBA6UKHkOZL8YCUU53Kt2mjGfC6dE3097xdoVo4LBNWKH91kcBELQhtZNZ0MUfsUO2G3HtYu0J1gsHei7u3cKWKP2Z4/brH2BvnVHXkPkqk5cwrF4O2uflnFnjeRLQduktC/f50DRK6J+njIz7mHf2BdChw4Of3l0/qNW+V66C7ccuVF1iEFpWIm4792p9EclsGF56hXlUrq9M+OEte0pDdaOimbJsWbjDb55a1wIjyyU/Jlwo/DMe0E5m7sr90AxAncXEKHOAmcjg6qJnlF1SoWdS2F+Xjlp4YiUOx4OK7ODK+dzmqt1pU8PRAeqdH39pJqyTIHPJhkv1OYNUjk64Kci2P+Dcw7vhY1tuBcSQOE466SpWtTIQMZy8bNeePb9JAXUuA6oiprnNo7pCXjen7hs7EvEn4CT1X/v9VBPFP9me5jxorQfTJZPzBuaLHOySxWiUiDwF7PyuHozJb0+YgYcJiQvuYtAa+0oz/hLBmVQ2xni49FjGsKDULfVJ5jS/yIY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
